services:
  - type: web
    name: crimenet-api
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: PORT
        value: 10000
